name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2

      - name: SSH to hosting server and update the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/hris.sadasa.id;
            git pull;
            composer install -q --no-ansi --no-interaction --no-progress --prefer-dist;
            php artisan key:generate;
            php artisan migrate;
